### ISSUE TITLE
Cannot compile & run: "kf" shorthand is more than one ASCII character

### ISSUE THREAD

**Issue by Restioson** [google/keytransparency#1295]
Hi. Upon installing (through `go get -u` as indicated in the readme) and running, I get this error:

```
panic: "kf" shorthand is more than one ASCII character

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc4200e0400, 0xc4201c1900)
	/home/restioson/go/src/github.com/spf13/pflag/flag.go:852 +0x7bc
github.com/spf13/pflag.(*FlagSet).VarPF(0xc4200e0400, 0xb69fa0, 0xec8be0, 0xae94fd, 0xb, 0xae34c8, 0x2, 0xaf25bc, 0x19, 0xc4201c1860)
	/home/restioson/go/src/github.com/spf13/pflag/flag.go:819 +0x120
github.com/spf13/pflag.(*FlagSet).VarP(0xc4200e0400, 0xb69fa0, 0xec8be0, 0xae94fd, 0xb, 0xae34c8, 0x2, 0xaf25bc, 0x19)
	/home/restioson/go/src/github.com/spf13/pflag/flag.go:825 +0x8e
github.com/spf13/pflag.(*FlagSet).StringVarP(0xc4200e0400, 0xec8be0, 0xae94fd, 0xb, 0xae34c8, 0x2, 0xae5d3d, 0x7, 0xaf25bc, 0x19)
	/home/restioson/go/src/github.com/spf13/pflag/string.go:42 +0xab
github.com/google/keytransparency/cmd/keytransparency-client/cmd.init.1()
	/home/restioson/go/src/github.com/google/keytransparency/cmd/keytransparency-client/cmd/hammer.go:58 +0x3d5
```

**Comment by mhutchinson** [comment]
This looks like it will be resolved by PR #1293.
